language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - >
    echo;
    echo "Running unit tests";
    echo;
    echo;
    php ./.Build/bin/phpunit -c Tests/Build/UnitTests.xml
  - >
    echo;
    echo "Running func tests";
    echo;
    echo;
    php ./.Build/bin/phpunit -c Tests/Build/FunctionalTests.xml
